forEach: Model
fileName: service.yaml
path: for-model/frontend/kubernetes
---
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: frontend